### ISSUE TITLE
Teams Reinstall - Per User Fix - QUSER Remediation Error...

### ISSUE THREAD

**Issue by wacado611** [microsoft/Windows365-PSScripts#15]
Thanks to the team creating these scripts, they will be a life saver if I can get them to work properly.

I'm using the Teams Reinstall - Per User Fix and am getting the following remediation error:

`quser : The term 'quser' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At C:\Windows\IMECache\HealthScripts\9bc64704-2ac2-4894-a0bd-2ed264464d77_1\remediate.ps1:54 char:8 + (((quser) -replace '^>', '') -replace '\s{2,}', ',').Trim() | For ... + ~~~~~ + CategoryInfo : ObjectNotFound: (quser:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException`

I'm interpreting the instructions as needing to run this script as "Run this script using the logged-on credentials" but I've tried not running as this as well, same error. I'm not sure if this is normal or if I'm doing something wrong.

My settings I'm using are:

![image](https://user-images.githubusercontent.com/108875509/180433509-4e45b8a7-5d39-429d-b7ed-746e65ff94bf.png)

Thanks in advance!
Cheers

**Comment by MietekW** [comment]
I run it with, are you using Cloud PC Enterprise or business?
Run this script using the logged-on credentials: No
Enforce script signature check:  No
Run script in 64-bit PowerShell: Yes


Also I see that the deployed cloud pcs, from end of last week are having the correct teams installed under user context.
So no need to run the teams fix anymore.

**Comment by wacado611** [comment]
We are using Cloud PC Enterprise.

I'll try changing my settings to what you are using (disabling run using logged on creds + enabling run script as 64-bit).

Right, the gallery images were fixed recently. I'm actually the one who made the ticket that got that accomplished...was a long ticket making my point, but finally got it done. I think they just duplicated the AVD gallery images and forgot about how the Teams install was done for those multi-session AVD's.

Thanks for your reply, I'll give the 64-bit option a try...maybe that's my hang-up.

Otherwise, it's running ok for you then? Are you NOT seeing the quser errors then?

**Comment by MietekW** [comment]
Thanks for your hard work on that case then :), those cases can indeed be quite time consuming with support engineers.
Yes it works a week 2 ago I tested it on a Cloud PC, when I start PowerShell in 32-bit(on my laptop) , the command quser also fails to run.
So I assume the 64bit will fix it for you.,

**Comment by wacado611** [comment]
Great, thank you for answering, sounds like that might fix it then. I should have tried that myself...   :/

Out of curiosity, since I've probably over-thought this like 10x, how did you end up on your parameters configuration? I 've been changing a few items back-n-forth, along with trying the $retry = $true, and can't settle on a final but currently am using this:
`Param(
    [parameter(mandatory = $false, HelpMessage = "Log path and file name")] 
    [string]$logpath = "$env:windir\temp\Teams-MWI-remediate.log",
    [parameter(mandatory = $false, HelpMessage = "time in seconds to wait past disconnect")]
    [string]$DCNTwait = 600,
    [parameter(mandatory = $false, HelpMessage = "time in seconds to wait to re-check user state")]
    [string]$StateDetWait = 300,
    [parameter(mandatory = $false, HelpMessage = "evaluate user state only once")] 
    [switch]$retry,
    #[switch]$retry = $true,
    [parameter(mandatory = $false, HelpMessage = "time in minutes to timeout")]
    [int]$TimeOut = 60
)`

**Comment by MietekW** [comment]
I left it default. I am still testing the script before releasing it to all impacted CPCs.
It is not working 100% as I would excpect it to do, when a user hasn't logged on to his CPC during the script ran, it doesn't seem to update it. The detection worked, I assume it has to do with the scheduled task, not running or able to start.

**Comment by wacado611** [comment]
We are still testing with IT too... We've had similar behaviors, but also the opposite, we've had it close Teams right in the middle of people using it, uninstall, and then not install back. This was prior to me changing to run as 64bit as you mentioned though, so maybe that was due to that.

Not sure if this script was tested prior to publishing...seems quirky so far...

**Comment by MietekW** [comment]
Yes be sure to go over the code yourself.
When the end-user logged on to the CPC the teams detection detected it was upgrade. (even though the event viewer showed it was upgraded already), I will continue to rollout, as the image is updated to have the latest teams, to get it over with and work on other things.

 I just noticed line: 441 in the remediation script contains a typo:
   remove-temm -path c:\windows\temp\teamsinstall.ps1 -force -ErrorAction Continue
   
   
![image](https://user-images.githubusercontent.com/48985193/181265980-2413b401-e93a-4fed-b604-78c93caa1393.png)

**Comment by DonnaRyanMicrosoft** [comment]
> Yes be sure to go over the code yourself. When the end-user logged on to the CPC the teams detection detected it was upgrade. (even though the event viewer showed it was upgraded already), I will continue to rollout, as the image is updated to have the latest teams, to get it over with and work on other things.
> 
> I just noticed line: 441 in the remediation script contains a typo: remove-temm -path c:\windows\temp\teamsinstall.ps1 -force -ErrorAction Continue
> 
> ![image](https://user-images.githubusercontent.com/48985193/181265980-2413b401-e93a-4fed-b604-78c93caa1393.png)

Good catch on the typo. I'll get that fixed shortly.

For OP, did switching to Run as 64 Bit PowerShell get rid of the QUSER issue for you?

**Comment by wacado611** [comment]
@DonnaRyanMicrosoft - Yes, switching to run as 64-bit did eliminate my quser error, thank you both.

**Comment by DonnaRyanMicrosoft** [comment]
Running script in 64 bit solved the problem. Typo pointed out on line 441 has been corrected. Added to readme.md to specify the Proactive Remediation settings. Should hit main branch in the next day
