### ISSUE TITLE
Windows365LanguagesInstaller does currently not support 21H2

### ISSUE THREAD

**Issue by Geo-Ron** [microsoft/Windows365-PSScripts#21]
The [Windows365LanguagesInstaller](https://www.powershellgallery.com/packages/Windows365LanguagesInstaller/) script does not support Windows 10 21H2.

Can this be provided or can I contribute?

**Comment by DonnaRyanMicrosoft** [comment]
If you want to fork the repo and dial in the script to support 21H2, you can.
